### ISSUE TITLE
allowUnfree error

### ISSUE THREAD

**Issue by unrooted** [applePrincess/hackpkgs#1]
hi, while developing both [RedNix](github.com/redcode-labs/RedNix) and [RedNixOS](github.com/redcode-labs/RedNixOS) I've decided that I'd love to add your packages there as well. However, it's exported with a Nixpkgs with `allowUnfree = false` which makes adding them to a devShell scope fail. Any ideas on what we can do? maybe you can provide us with an overlay? our current workaround would be having `~/.config/nixpkgs/nix.conf` with a desired option as well as passing `--impure` flag

**Comment by applePrincess** [comment]
Sounds good! I will create an overlay that only contains free packages.

**Comment by unrooted** [comment]
Thanks a lot, however, if doable, adding unfree ones would be greatly appreciated, they're the reason why I'm here
